apiVersion: v1
kind: Service
metadata:
  annotations:
    kubecfg.ksonnet.io/garbage-collect-tag: bitnami/kubeapps
 
  labels:
    app: kubeapps
    created-by: kubeapps
    name: kubeapps
  name: kubeapps
  namespace: kubeapps
 
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: kubeapps
    name: kubeapps
  sessionAffinity: None
  type: LoadBalancer

