kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: thin-disk
provisioner: kubernetes.io/vsphere-volume
parameters:
    datastore: Datastore-NFS-VM
    diskformat: thin
    fstype: ext3

